### ISSUE TITLE
Check hazard module

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#115]
The top xarray content is hydromt_fiat output, the bottom is how it 'should' look:

@Mares2022 let's discuss it next week

![MicrosoftTeams-image](https://github.com/Deltares/hydromt_fiat/assets/72015981/4cbb5f4f-7f91-4c35-9b78-64e6e3c8cc85)

**Comment by Mares2022** [comment]
I modified the code to avoid using the geom parameter in .get_rasterdataset(). https://deltares.github.io/hydromt/latest/_generated/hydromt.data_catalog.DataCatalog.get_rasterdataset.html#hydromt.data_catalog.DataCatalog.get_rasterdataset

Hydromt core creates a mask in the netcdf file when assigning self.region (from fiat.py) as geometry.

3436286512f243b4fec352ca2cb8cdaea2421a1a

The new hazard maps can be found here: P:\11207949-dhs-phaseii-floodadapt\Model-builder\Delft-FIAT\local_test_database\Hazard_maps

**Comment by Mares2022** [comment]
I modified the code to avoid using the geom parameter in .get_rasterdataset(). https://deltares.github.io/hydromt/latest/_generated/hydromt.data_catalog.DataCatalog.get_rasterdataset.html#hydromt.data_catalog.DataCatalog.get_rasterdataset

Hydromt core creates a mask in the netcdf file when assigning self.region (from fiat.py) as geometry.

3436286512f243b4fec352ca2cb8cdaea2421a1a
