### ISSUE TITLE
Implement option to link exposure points to a spatial building footprint file for visualization

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#133]
When the user starts to build a FIAT model with building footprints, that will also be the output from HydroMT-FIAT. When a user creates a FIAT model with points as exposure locations, e.g., from NSI data, then the user might want to visualize the calculated damages/risk with building footprints instead of points. In the FIAT Toolbox (https://github.com/Deltares/fiat_toolbox) there is a script to join the results (csv) with the building footprints but this requires the exposure.csv input data to have a column to link the objects to the building footprints. We call this attribute standard 'BF_FID' (building footprint feature ID). 

A function should be implemented in HydroMT FIAT to create this column from input data and put the spatial file in a folder called 'footprints' in the main FIAT output folder. This might not be the best and most logical location but it should be discussed with the FloodAdapt team when we alter this as FloodAdapt is now expecting it to be in that location.

**Comment by savente93** [comment]
this is marked as done, so closing it
