### ISSUE TITLE
Allow to use different names for the spatial exposure data

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#137]
- [x] When a model is read in, HydroMT-FIAT should take the same name of the input data for the output (e.g. if a user has a buildings.gpkg and roads.gpkg, the output should also have these names)
- [x] When a model is created from scratch, give more explanatory names like 'exposure_points.gpkg' instead of 'exposure1.gpkg'

**Comment by savente93** [comment]
this is marked as done, so closing it
