### ISSUE TITLE
Update maximum potential damages with user-input data

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#145]
Different options to join the data to the exposure data:

- [ ] Nearest neighbor
- [ ] Intersection (spatial join)

Other features:

- [ ] Add the option to use for a certain damage type: structure, content, or something else.
- [ ] Add the option to use certain data sources before other data sources (e.g., use user-input data where ever that is available and use the NSI data for the locations where there is no data, similarly to #125

**Comment by savente93** [comment]
this is marked as done, so closing it
