### ISSUE TITLE
pip -e . not working

### ISSUE THREAD

**Issue by Mares2022** [Deltares/hydromt_fiat#193]
Intallation of hydromt-fiat-dev is working, but when running pip install -e . the console shows this message. 
![image](https://github.com/Deltares/hydromt_fiat/assets/117270047/d1caeeec-8e56-400a-868b-6be42ce2e773)

**Comment by savente93** [comment]
From the screenshot it seems that you are not in the folder of hydromt_fiat but instead of your home folder. It should work if you enter the correct directly. Feel free to reopen this if you still have issues after that
