### ISSUE TITLE
Set up local database with US data for testing purposes

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#23]
For Charleston, with the data that Luis defined for the sprint end goal.

**Comment by frederique-hub** [comment]
Mario

**Comment by Mares2022** [comment]
@luisrodriguezgalvez will create this database together with the vulnerability database described in issue #24

**Comment by luisrodriguezgalvez** [comment]
It can be found on P:\11207058-fiat-objects-interface\7. Project test data [INTERNAL USE ONLY]\Model Builder
