### ISSUE TITLE
[GUI] Add unit to threshold value for OSM roads (exposure/start tab)

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#238]
- [x] bug when adding road manually 
- [x] And add an info button for the threshold value

**Comment by kathrynroscoe** [comment]
Let's do something similar to what we do in FloodAdapt in terms of asking for units and then converting (if necessary) in the backend. That's why I'm adding Gundula and Daley, to give guidance how to do this in the model-builder.

**Comment by Santonia27** [comment]
The threshold value is indicated here in ft. Should the user be able to also set the value in metres and then we do the conversion in the backend? 
The issue title talks about something else than the description. In the description only an info button is requested.
