### ISSUE TITLE
[GUI] Finished floor height tab

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#240]
- [x] Add choosing the default option for merging.
- [x]  With point data input, choose nearest and with polygon input, choose intersection
- [x] Test manually 

use fake_elevation_certificate.gpkg as testinput

**Comment by kathrynroscoe** [comment]
This is implemented but needs testing before sending for review

**Comment by Santonia27** [comment]
There were issues with building the config file and running the update_ground_floor_height function. 
I solved the issue but asked for review from the code-experts to see if there is a smoother solution

**Comment by Santonia27** [comment]
Changed the term "method" to "gfh_method"
