### ISSUE TITLE
Make the existance of the data catalog optional or provide a default catalog with no confidential information

### ISSUE THREAD

**Issue by LuukBlom** [Deltares/hydromt_fiat#276]
Currently, when using hydromt_fiat in another project (delftdashboard currently), I get an error if I install hydromt_fiat as a git package. 
The error is caused in the initialization and says it cant find the data catalog (as its not in the repo). 

So we should make it flexible and not raise an error if there is no datacatalog, and ask for user input of a catalog.
Or maybe have a default data catalog without confidential data in the repo

**Comment by Santonia27** [comment]
data is openly shared
