### ISSUE TITLE
When using a DEM for updating FIAT ground elevation, unit conversion should take place

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#294]
Right now, when the ground elevation of a FIAT model is updated with a DEM there is unit conversion taking place. For example, if you use the GUI to update the ground elevation from a SFINCS model, the units will be in meters, but FIAT will interpret them as feet, creating wrong results.

The method should always require a unit for the DEM used, and for the GUI case of using a SFINCS model, we can assume that the units from SFINCS are always meters.

**Comment by Santonia27** [comment]
additional variable (unit) set_ground_elevation
for SFINCS default meters
