### ISSUE TITLE
Geoms when reading a FIAT model appear two times in the objects

### ISSUE THREAD

**Issue by panosatha** [Deltares/hydromt_fiat#295]
When reading an existing FIAT model, it seems that the FiatModel.exposire.exposure_geoms appear twice in the list:

![image](https://github.com/Deltares/hydromt_fiat/assets/38324721/eba62303-8f79-4983-8cd7-08c31cfafd5a)

**Comment by Santonia27** [comment]
Didnt happen anymore. Possibly solved with other bugfixes
