### ISSUE TITLE
Define the sprint end-goal demo workflow

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#32]

**Comment by luisrodriguezgalvez** [comment]
Assign to me

**Comment by luisrodriguezgalvez** [comment]
Use case defined as sprint demo end goal:
- Follow user storyline going through the following steps building the required input in the right format and folder structure to run FIAT:
   - Exposure:
      - Point data on building locations from NSI (https://www.hec.usace.army.mil/confluence/nsi/)
      - Object (building) classification data from NSI
      - Maximum potential damages per class from NSI
      - (One) aggregation label
   - Hazard:
      - Local file input
   - Vulnerability:
      -  Damage functions from HAZUS (https://github.com/nhrap-hazus/FAST/blob/main/Lookuptables/AllDDF.xlsx)

See "C:\Users\rodrigue\OneDrive - Stichting Deltares\Desktop\Other Projects\2023_01 FIAT Model Builder\model_builder_sprint_goal_use_case.drawio" for full diagram for this sprint

See "N:\Projects\11204000\11204196\F. Other information\15 - Design\Model Builder\model_builder_sprint_goal_use_case.drawio" for details.

**Comment by frederique-hub** [comment]
Use Charleston as location.
We can find aggregation data here: https://data-charleston-sc.opendata.arcgis.com/
